services:
  rabbitmq:
    image: rabbitmq:3.13.4-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - .docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - .docker-conf/rabbitmq/log/:/var/log/rabbitmq
        - ./rabbitmq/:/etc/rabbitmq
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge