apiVersion: v1
kind: Namespace
metadata:
  name: cpu-bound-workers

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-environment
  namespace: cpu-bound-workers
data:
  RABBITMQ_ERLANG_COOKIE: "some-secret-cookie"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: cpu-bound-workers
data:
  definitions.json: |
    {  "rabbit_version": "3.13.4",  "rabbitmq_version": "3.13.4",  "product_name": "RabbitMQ",  "product_version": "3.13.4",  "users": [    {      "name": "guest",      "password_hash": "XxT7aqXuhRN0MIi7UP0j4Bb5Yr1y7LA4p3DkAxr6pF1uimjl",      "hashing_algorithm": "rabbit_password_hashing_sha256",      "tags": [        "administrator"      ],      "limits": {}    }  ],  "vhosts": [    {      "name": "/",      "description": "Default virtual host",      "tags": [],      "metadata": {        "description": "Default virtual host",        "tags": []      }    }  ],  "permissions": [    {      "user": "guest",      "vhost": "/",      "configure": ".*",      "write": ".*",      "read": ".*"    }  ],  "topic_permissions": [],  "parameters": [],  "global_parameters": [    {      "name": "internal_cluster_id",      "value": "rabbitmq-cluster-id-TQ_5DP8J8JjPyTFLpn9McA"    }  ],  "policies": [],  "queues": [    {      "name": "matrix-multiplication-worker",      "vhost": "/",      "durable": true,      "auto_delete": false,      "arguments": {}    }  ],  "exchanges": [    {      "name": "matrix-multiplication",      "vhost": "/",      "type": "direct",      "durable": true,      "auto_delete": false,      "internal": false,      "arguments": {}    }  ],  "bindings": [    {      "source": "matrix-multiplication",      "vhost": "/",      "destination": "matrix-multiplication-worker",      "destination_type": "queue",      "routing_key": "worker",      "arguments": {}    }  ]}
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_prometheus].
  rabbitmq.conf: |
    loopback_users.guest = false
    log.console = true
    definitions.skip_if_unchanged = true
    definitions.import_backend = local_filesystem
    definitions.local.path = /etc/rabbitmq/definitions.json


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: cpu-bound-workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13.4-management
          envFrom:
          - configMapRef:
              name: rabbitmq-environment
          ports:
          - containerPort: 5672
          - containerPort: 15672
          volumeMounts:
          - name: rmq-config
            mountPath: "/etc/rabbitmq"
            readOnly: true
      volumes:
      - name: rmq-config
        configMap:
          name: rabbitmq-config
          items:
          - key: "definitions.json"
            path: "definitions.json"
          - key: "enabled_plugins"
            path: "enabled_plugins"
          - key: "rabbitmq.conf"
            path: "rabbitmq.conf"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: cpu-bound-workers
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      name: "service"
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: cpu-bound-workers
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      targetPort: 15672
      name: "management"
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: cpu-bound-workers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: cpu-bound-worker-api:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: MATRIX_MULTIPLICATION_EXCHANGE
          value: "matrix-multiplication"
        - name: MATRIX_MULTIPLICATION_WORKER_ROUTING_KEY
          value: "worker"

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: cpu-bound-workers
spec:
  selector:
    app: api
  ports:
    - port: 8005
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: cpu-bound-workers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: cpu-bound-worker-service:2
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBIT_MQ_HOST
          value: "localhost"
        - name: MATRIX_MULTIPLICATION_WORKER_QUEUE
          value: "matrix-multiplication-worker"
